# Generated by Django 5.1.1 on 2024-10-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cont',
            field=models.CharField(max_length=14, verbose_name='Contact Number'),
        ),
    ]
