# Generated by Django 5.1.1 on 2024-10-19 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0003_alter_contact_cont_alter_contact_emailad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confpass',
        ),
        migrations.AlterField(
            model_name='adminn',
            name='enddate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='adminn',
            name='institute',
            field=models.CharField(choices=[('OPTION 1', 'Option 1'), ('OPTION 2', 'Option 2'), ('OPTION 3', 'Option 3')], max_length=50),
        ),
        migrations.AlterField(
            model_name='adminn',
            name='startdate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='candidacyform',
            name='birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='candidacyform',
            name='cotn',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='candidacyform',
            name='emailaddr',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidacyform',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidacyform',
            name='position',
            field=models.CharField(choices=[('SELECT', 'Select'), ('OPTION 1', 'Option 1'), ('OPTION 2', 'Option 2')], max_length=50),
        ),
        migrations.AlterField(
            model_name='candidacyform',
            name='statement',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cont',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='letter',
            field=models.FileField(upload_to='static/credentials/letters'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='others',
            field=models.FileField(upload_to='static/credentials/others'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='quali',
            field=models.FileField(upload_to='static/credentials/qualifications'),
        ),
        migrations.AlterField(
            model_name='credentials',
            name='resume',
            field=models.FileField(upload_to='static/credentials/resume'),
        ),
        migrations.AlterField(
            model_name='login',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='login',
            name='userid',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='registration',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='registration',
            name='contact',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='registration',
            name='emailadd',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='gender',
            field=models.CharField(choices=[('SELECT', 'Select'), ('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='idnum',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='idtype',
            field=models.CharField(choices=[('OPTION 1', 'Option 1'), ('OPTION 2', 'Option 2'), ('OPTION 3', 'Option 3')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='lname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='password',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='suffix',
            field=models.CharField(choices=[('NONE', 'None'), ('Sr.', 'Sr.'), ('Jr.', 'Jr.'), ('II', 'II')], max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='uid',
            field=models.CharField(max_length=100),
        ),
    ]
