# Generated by Django 5.1.1 on 2024-10-22 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0005_rename_adminn_adminnform_rename_contact_contactform_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidacyform',
            new_name='candidacyformm',
        ),
    ]
