# Generated by Django 5.1.1 on 2024-10-23 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0006_rename_candidacyform_candidacyformm'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='candidacyformm',
            new_name='candidacy_form',
        ),
    ]
