# Generated by Django 5.1.1 on 2024-10-23 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0007_rename_candidacyformm_candidacy_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='resetpass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=150, unique=True)),
                ('newpass', models.CharField(max_length=150)),
                ('confirmpass', models.CharField(max_length=150)),
            ],
        ),
    ]
