# Generated by Django 5.1.1 on 2024-10-23 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0008_resetpass'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginform',
            old_name='userid',
            new_name='uid',
        ),
        migrations.RenameField(
            model_name='resetpass',
            old_name='userid',
            new_name='uid',
        ),
        migrations.AlterModelTable(
            name='loginform',
            table='loginform',
        ),
    ]
