# Generated by Django 5.1.1 on 2024-10-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0009_rename_userid_loginform_uid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='uid',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
