# Generated by Django 5.1.1 on 2024-11-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0010_alter_registrationform_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='comelec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100, verbose_name='First Name')),
                ('mname', models.CharField(blank=True, max_length=100, verbose_name='Middle Name')),
                ('lname', models.CharField(max_length=100, verbose_name='Last Name')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('SELECT', 'Select'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='SELECT', max_length=10)),
                ('suffix', models.CharField(choices=[('NONE', 'None'), ('Sr.', 'Sr.'), ('Jr.', 'Jr.'), ('II', 'II')], default='NONE', max_length=10)),
                ('idtype', models.CharField(choices=[('OPTION 1', 'Option 1'), ('OPTION 2', 'Option 2'), ('OPTION 3', 'Option 3')], default='OPTION 1', max_length=10)),
                ('idnum', models.CharField(max_length=100, verbose_name='ID Number')),
                ('uid', models.CharField(max_length=100, unique=True, verbose_name='User ID')),
                ('emailadd', models.EmailField(max_length=100, verbose_name='Email Address')),
                ('contact', models.CharField(max_length=15, verbose_name='Contact Number')),
            ],
        ),
    ]
