# Generated by Django 5.1.1 on 2024-11-08 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0011_comelec'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='comelec',
            new_name='comelecform',
        ),
    ]
