# Generated by Django 5.1.1 on 2025-01-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0013_movieinfo_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnform',
            name='others1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminnform',
            name='others2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminnform',
            name='others3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminnform',
            name='positions',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='enddate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='institute',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='startdate',
            field=models.DateField(),
        ),
    ]
