# Generated by Django 5.1.1 on 2025-01-07 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0015_adminnform_others4'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminnform',
            name='others5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
