# Generated by Django 5.1.1 on 2025-01-07 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0016_adminnform_others5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminnform',
            name='institute',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='others1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='others2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='others3',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='others4',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminnform',
            name='others5',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
