# Generated by Django 5.1.1 on 2025-01-08 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0017_alter_adminnform_institute_alter_adminnform_others1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='candidates/')),
            ],
        ),
        migrations.CreateModel(
            name='vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('vote1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote1', to='ovs.candidate')),
                ('vote2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote2', to='ovs.candidate')),
                ('vote3', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote3', to='ovs.candidate')),
            ],
        ),
    ]
