# Generated by Django 5.1.1 on 2025-01-08 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0018_candidate_vote'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vote',
            new_name='voteform',
        ),
    ]
