# Generated by Django 5.1.4 on 2025-01-08 10:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ovs', '0019_rename_vote_voteform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='photo',
        ),
        migrations.AddField(
            model_name='candidate',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='candidate',
            name='cotn',
            field=models.CharField(default='N/A', max_length=15),
        ),
        migrations.AddField(
            model_name='candidate',
            name='credential1',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='credential2',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='credential3',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='credential4',
            field=models.FileField(blank=True, null=True, upload_to='credentials/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='emailaddr',
            field=models.EmailField(default='N/A', max_length=254),
        ),
        migrations.AddField(
            model_name='candidate',
            name='fullname',
            field=models.CharField(default='John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='candidate',
            name='statement',
            field=models.TextField(blank=True, default='No statement provided', null=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='position',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
